apiVersion: apps/v1
kind: Deployment
metadata:
  name: churn-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: { app: churn-service }
  template:
    metadata:
      labels: { app: churn-service }
    spec:
      containers:
      - name: api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports: [{ containerPort: 8000 }]
        readinessProbe:
          httpGet: { path: /health, port: 8000 }
